@startuml
allowmixing
package "Calculator End-To-End Tests via Playwright" #lightyellow {
    class CalculatorEndToEndTests {
        + CalculatorUI_PageTitle_ReturnsCalculator()
        + CWebCalculator_ComputeZScore_ReturnResult()
        + WebCalculator_PredictY_ReturnResult()
        + WebCalculator_ComputePopulationStdDev_ReturnsResult()
    }

    CalculatorEndToEndTests --> Controllers : HTTP Call to Calculator Web Server App
}
@enduml
