@startuml
allowmixing
package "Calculator Logic Unit Tests via JUnit" #lightyellow {
    class LogicUnitTests {
        + DescriptiveStatistics_computeMean_ReceiveNullValueList_ThrowException()
        + DescriptiveStatistics_computeMean_ReceiveEmptyValueList_ThrowException()
        + DescriptiveStatistics_computeMean_ReceiveNonNumericValue_ThrowException()
        + LinearRegression_computeLinearRegressionFormula_ReceiveValidValues_ReturnsLinearRegressionFormula()
    }

    LogicUnitTests --> DescriptiveStatistics
    LogicUnitTests --> LinearRegression
}
@enduml
