name: Run Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
      - uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
              ${{ runner.os }}-maven-


      - name: Install Playwright dependencies
        run: |
          npx playwright install


      - name: Install dependencies
        run: |
          mvn clean install
          
      - name: Start Web Application with Maven
        run: |
          mvn -pl src/web spring-boot:run

          while ! curl -s http://localhost:8080/ > /dev/null; do
            echo "Waiting for application to start..."
            sleep 5
          done


      - name: Run tests
        run: mvn test

